"""Train PyTorch models through low-dimensional parameter mappings."""

from marn.generators import (
    GroupedGenerator,
    LayerGenerator,
    LazyLayerwiseGenerator,
    LayerwiseGenerator,
    ParameterGenerator,
    SingleVectorGenerator,
    FineTuningGenerator,
    LRDGenerator,
)
from marn.distributed import (
    benchmark_strategies,
    cleanup_ddp,
    is_ddp_available,
    profile_peak_memory,
    setup_ddp,
    wrap_ddp,
)
from marn.models import (
    ForwardResult,
    MappingModel,
    TargetModel,
    UnsupportedTargetModelError,
)
from marn.losses import (
    AlignmentLoss,
    BaseLoss,
    ClassificationLoss,
    LossOutput,
    MappingLoss,
    RegressionLoss,
    SmoothnessLoss,
    StabilityLoss,
    TaskLoss,
    TrainingContext,
)
from marn.mappers import BaseMapper, MLPMapper, ResidualMLPMapper
from marn.modulation import (
    AdditiveModulation,
    AffineModulation,
    BaseModulation,
    LowRankModulation,
)
from marn.runtime import ParameterEntry, ParameterSpec, ParameterTree
from marn.strategies import (
    GroupedStrategy,
    LayerwiseStrategy,
    SLVTStrategy,
    FineTuningStrategy,
    LRDStrategy,
)
from marn.config import (
    GeneratorConfig,
    LossConfig,
    MapperConfig,
    MappingConfig,
    TaskLossConfig,
    TrainerConfig,
    load_config,
)
from marn.registry import (
    GENERATOR_REGISTRY,
    LOSS_REGISTRY,
    MAPPER_REGISTRY,
    MODULATION_REGISTRY,
    Registry,
)
from marn.callbacks import Callback, EarlyStopping, MetricLogger
from marn.trainers import (
    BatchAdapter,
    MappingBatchAdapter,
    MappingTrainer,
    TupleBatchAdapter,
    LRFinderResult,
)
from marn.checkpoint import (
    CheckpointCompatibilityError,
    CheckpointSchema,
    load_checkpoint,
    save_checkpoint,
)

__all__ = [
    "AdditiveModulation",
    "AffineModulation",
    "AlignmentLoss",
    "BaseLoss",
    "BaseMapper",
    "BaseModulation",
    "BatchAdapter",
    "Callback",
    "CheckpointCompatibilityError",
    "CheckpointSchema",
    "ClassificationLoss",
    "EarlyStopping",
    "ForwardResult",
    "FineTuningGenerator",
    "GENERATOR_REGISTRY",
    "GeneratorConfig",
    "GroupedGenerator",
    "GroupedStrategy",
    "LOSS_REGISTRY",
    "LayerGenerator",
    "LazyLayerwiseGenerator",
    "LayerwiseGenerator",
    "LayerwiseStrategy",
    "LRDGenerator",
    "LossConfig",
    "LossOutput",
    "LowRankModulation",
    "MAPPER_REGISTRY",
    "MODULATION_REGISTRY",
    "MapperConfig",
    "MappingBatchAdapter",
    "MappingConfig",
    "MappingLoss",
    "MappingModel",
    "MappingTrainer",
    "MLPMapper",
    "MetricLogger",
    "ParameterEntry",
    "ParameterGenerator",
    "ParameterSpec",
    "ParameterTree",
    "RegressionLoss",
    "Registry",
    "ResidualMLPMapper",
    "SLVTStrategy",
    "SingleVectorGenerator",
    "FineTuningStrategy",
    "LRDStrategy",
    "LRFinderResult",
    "SmoothnessLoss",
    "StabilityLoss",
    "TargetModel",
    "TaskLoss",
    "TaskLossConfig",
    "TrainerConfig",
    "TrainingContext",
    "TupleBatchAdapter",
    "UnsupportedTargetModelError",
    "benchmark_strategies",
    "cleanup_ddp",
    "is_ddp_available",
    "load_checkpoint",
    "load_config",
    "profile_peak_memory",
    "save_checkpoint",
    "setup_ddp",
    "wrap_ddp",
]
__version__ = "0.1.0"
